# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'windowaviso.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Aviso(object):
    def setupUi(self, Aviso):
        Aviso.setObjectName("Aviso")
        Aviso.setWindowModality(QtCore.Qt.ApplicationModal)
        Aviso.resize(253, 235)
        Aviso.setModal(True)
        self.BtnBoxAviso = QtWidgets.QDialogButtonBox(Aviso)
        self.BtnBoxAviso.setGeometry(QtCore.QRect(-40, 160, 341, 91))
        self.BtnBoxAviso.setAutoFillBackground(False)
        self.BtnBoxAviso.setOrientation(QtCore.Qt.Horizontal)
        self.BtnBoxAviso.setStandardButtons(QtWidgets.QDialogButtonBox.No|QtWidgets.QDialogButtonBox.Yes)
        self.BtnBoxAviso.setCenterButtons(True)
        self.BtnBoxAviso.setObjectName("BtnBoxAviso")
        self.lblimgAviso = QtWidgets.QLabel(Aviso)
        self.lblimgAviso.setGeometry(QtCore.QRect(70, 20, 111, 101))
        self.lblimgAviso.setText("")
        self.lblimgAviso.setPixmap(QtGui.QPixmap("img/aviso.png"))
        self.lblimgAviso.setScaledContents(True)
        self.lblimgAviso.setObjectName("lblimgAviso")
        self.lblAviso = QtWidgets.QLabel(Aviso)
        self.lblAviso.setGeometry(QtCore.QRect(70, 140, 121, 20))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lblAviso.setFont(font)
        self.lblAviso.setObjectName("lblAviso")

        self.retranslateUi(Aviso)
        self.BtnBoxAviso.accepted.connect(Aviso.accept)
        self.BtnBoxAviso.rejected.connect(Aviso.reject)
        QtCore.QMetaObject.connectSlotsByName(Aviso)

    def retranslateUi(self, Aviso):
        _translate = QtCore.QCoreApplication.translate
        Aviso.setWindowTitle(_translate("Aviso", "Aviso"))
        self.lblAviso.setText(_translate("Aviso", "Desea Salir?"))
