# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'windowcal.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_windowcal(object):
    def setupUi(self, windowcal):
        """

        Generado por QtDesigner, para la ventana de calendario
        :param interfaz gráfica:
        :type windowcal:

        """
        windowcal.setObjectName("windowcal")
        windowcal.resize(311, 182)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../.designer/backup/img/fechas.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        windowcal.setWindowIcon(icon)
        windowcal.setModal(True)
        self.calendar = QtWidgets.QCalendarWidget(windowcal)
        self.calendar.setGeometry(QtCore.QRect(0, 0, 312, 183))
        self.calendar.setObjectName("calendar")

        self.retranslateUi(windowcal)
        QtCore.QMetaObject.connectSlotsByName(windowcal)

    def retranslateUi(self, windowcal):
        _translate = QtCore.QCoreApplication.translate
        windowcal.setWindowTitle(_translate("windowcal", "Seleccione Fecha"))
